#!/bin/bash
###############################################################
#                Unofficial 'Bash strict mode'                #
# http://redsymbol.net/articles/unofficial-bash-strict-mode/  #
###############################################################
set -euo pipefail
IFS=$'\n\t'
###############################################################

interface_is_up() {
	local interface="${1}"

	if ip a show "${interface}" up &>/dev/null; then
		return 0
	else
		return 1
	fi
}

overlay_is_loaded() {
	overlay_name="${1}"
	if dtoverlay -l | grep -q "${overlay_name}$"; then
		return 0
	else
		return 1
	fi
}

unload_overlay() {
	overlay_name="${1}"
	# Remove if loaded
	if overlay_is_loaded "${overlay_name}"; then
		echo "Unloading ${overlay_name} dtoverlay"
		dtoverlay -r "${overlay_name}"
	fi
}

load_overlay() {
	overlay_name="${1}"
	unload_overlay "${overlay_name}"
	echo "Loading ${overlay_name} dtoverlay"
	dtoverlay "${overlay_name}"
}

load_overlay "dwc2"

if ! interface_is_up ptusb0; then
	echo "USB-OTG interface 'ptusb0' is not up. Nothing to do..."
	unload_overlay "dwc2"
fi
