#!/bin/bash
###############################################################
#                Unofficial 'Bash strict mode'                #
# http://redsymbol.net/articles/unofficial-bash-strict-mode/  #
###############################################################
set -euo pipefail
IFS=$'\n\t'
###############################################################

interface_is_up() {
	local interface="${1}"

	if ip a show "${interface}" up &>/dev/null; then
		return 0
	else
		return 1
	fi
}

overlay_is_loaded() {
	overlay_name="${1}"
	status_file=""

	if [ "${overlay_name}" == "dwc2" ]; then
		status_file="/proc/device-tree/soc/usb@7e980000/status"
	else
		return 1
	fi

	if grep -s -q okay "${status_file}"; then
		return 0
	else
		return 1
	fi
}

unload_overlay() {
	overlay_name="${1}"
	# Remove if loaded
	if overlay_is_loaded "${overlay_name}"; then
		echo "Unloading ${overlay_name} dtoverlay"
		dtoverlay -r "${overlay_name}"
	fi
}

load_overlay() {
	overlay_name="${1}"
	unload_overlay "${overlay_name}"
	echo "Loading ${overlay_name} dtoverlay"
	dtoverlay "${overlay_name}"
	sleep 1
}

remove_kernel_modules() {
	modprobe -rf dwc2 || true
	modprobe -rf g_ether || true
}

load_kernel_modules() {
	remove_kernel_modules
	modprobe dwc2
	modprobe g_ether dev_addr=00:11:22:33:44:55
}

wait_for_interface() {
	local interface="${1}"
	local time_to_wait="${2}"
	echo "Waiting for '${interface}' interface for up to ${time_to_wait} seconds..."

	COUNTER=1
	while [ $COUNTER -le "${time_to_wait}" ]; do
		if interface_is_up "${interface}"; then
			echo "Interface '${interface}' is up!"
			break
		fi
		echo "Sleeping for 1 sec waiting for '${interface}' interface..."
		sleep 1
		COUNTER=$((COUNTER + 1))
	done
}

main() {
	load_overlay "dwc2"
	load_kernel_modules

	wait_for_interface ptusb0 5
	if ! interface_is_up ptusb0; then
		echo "USB-OTG interface 'ptusb0' is not up. Nothing to do..."
		unload_overlay "dwc2"
		remove_kernel_modules
		return
	fi

	# Set static IP for interface if found
	ifconfig ptusb0 192.168.64.1
}

main
